[server]
headless = true
port = 8080
address = "0.0.0.0"
enableStaticServing = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8080

[client]
toolbarMode = "viewer"
showSidebarNavigation = false

[ui]
hideTopBar = true

[theme]
base = "light"